//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanpuchi.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kanpuchi.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   about app に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ABOUT APP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackMenu {
            get {
                return ResourceManager.GetString("BackMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CloseMenu {
            get {
                return ResourceManager.GetString("CloseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   general に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralTitle {
            get {
                return ResourceManager.GetString("GeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   license に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LicenseTitle {
            get {
                return ResourceManager.GetString("LicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load data. Try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadErrorMessage {
            get {
                return ResourceManager.GetString("LoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadErrorTitle {
            get {
                return ResourceManager.GetString("LoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading data... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadProgress {
            get {
                return ResourceManager.GetString("LoadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KANPUCHI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   matome に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MatomeTitle {
            get {
                return ResourceManager.GetString("MatomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveBottomMenu {
            get {
                return ResourceManager.GetString("MoveBottomMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveTopMenu {
            get {
                return ResourceManager.GetString("MoveTopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   open url に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenUrlMenu {
            get {
                return ResourceManager.GetString("OpenUrlMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   open with browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenWithBrowserMenu {
            get {
                return ResourceManager.GetString("OpenWithBrowserMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Privacy policy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrivacyPolicyLabel {
            get {
                return ResourceManager.GetString("PrivacyPolicyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   read more に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReadMoreButton {
            get {
                return ResourceManager.GetString("ReadMoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Review app に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReviewAppLabel {
            get {
                return ResourceManager.GetString("ReviewAppLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SETTINGS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   share に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShareMenu {
            get {
                return ResourceManager.GetString("ShareMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartProgress {
            get {
                return ResourceManager.GetString("StartProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   timeline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TimelineTitle {
            get {
                return ResourceManager.GetString("TimelineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateMenu {
            get {
                return ResourceManager.GetString("UpdateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use app browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UseAppInBrowserLabel {
            get {
                return ResourceManager.GetString("UseAppInBrowserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionTitle {
            get {
                return ResourceManager.GetString("VersionTitle", resourceCulture);
            }
        }
    }
}
